// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_EhXvXsd95ybGlufqlet_nh4uQz7zf_8',
    appId: '1:278678277346:web:c13e4090dad0b8adcb22bb',
    messagingSenderId: '278678277346',
    projectId: 'chat-app-58cb7',
    authDomain: 'chat-app-58cb7.firebaseapp.com',
    storageBucket: 'chat-app-58cb7.firebasestorage.app',
    measurementId: 'G-25JJYVHNGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwHZNefq_B1qfRSA2GjygoDNfbTxoUbYs',
    appId: '1:278678277346:android:376e6b8f8a075b18cb22bb',
    messagingSenderId: '278678277346',
    projectId: 'chat-app-58cb7',
    storageBucket: 'chat-app-58cb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkWu22SFcjwSATeuOvG6yhgVD0XrFrTC0',
    appId: '1:278678277346:ios:e14fd04c0b6779d8cb22bb',
    messagingSenderId: '278678277346',
    projectId: 'chat-app-58cb7',
    storageBucket: 'chat-app-58cb7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkWu22SFcjwSATeuOvG6yhgVD0XrFrTC0',
    appId: '1:278678277346:ios:e14fd04c0b6779d8cb22bb',
    messagingSenderId: '278678277346',
    projectId: 'chat-app-58cb7',
    storageBucket: 'chat-app-58cb7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_EhXvXsd95ybGlufqlet_nh4uQz7zf_8',
    appId: '1:278678277346:web:037929f1e2b8af83cb22bb',
    messagingSenderId: '278678277346',
    projectId: 'chat-app-58cb7',
    authDomain: 'chat-app-58cb7.firebaseapp.com',
    storageBucket: 'chat-app-58cb7.firebasestorage.app',
    measurementId: 'G-MPR2ZVXLF6',
  );
}
